### ISSUE TITLE
Server side event when a file upload is complete

### ISSUE THREAD

**Issue by max-l** [edihasaj/tuspy-fast-api#2]
It would be nice to get a server side callback when an upload is complete (last chunk received),
in this callback one could move the file from  where it's at (currently  hardcoded at /tmp/files/ae76a377ce0e44f3897d5542aca8067a)
and give it a proper name (for ex. the name on the client machine).

I guess the way to do this currently, would be to use the callback on the client side, and send a request to the server with 
the file UUID, to move the file.

Also, is there a plan to unhardcode the following values  (port = 8000, and FILES_DIR = '/tmp/files') ? : 

https://github.com/edihasaj/tuspy-fast-api/blob/main/tusserver/tus.py#L14

https://github.com/edihasaj/tuspy-fast-api/blob/main/tusserver/tus.py#L130

**Comment by edihasaj** [comment]
Hey Max, thanks a lot for checking in. Can you be more descriptive of the callback on the client side, you mean to upload it in Google drive, etc.?

As for the hardcoded values it was a bit of an issue when I started implementing TUS since I cannot make it parametrized, but of course what I can do is make a way to query some standard app config and if you set them there, then we use that path. This was developed fast, and in every case that I did use this code I did change the things to my likings and business logic.

I will check when I have a bit time maybe by then of the week, though changes are welcomed as well 🥇

**Comment by edihasaj** [comment]
@max-l thanks for the good thinking you put into this. working with callback actually works and in tus we have this PATCH request where we can check the file chunks if they are the same as they should be if so we complete the file uploading at the end if there is a callback declared we can just invoke it. So that's a very good idea of yours. Also I like the way of using create_api_router, we can set the parameters inside to de-clutch our hardcoded variables.
